/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.MedicineCatalog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class CatalogJPanel extends javax.swing.JPanel {
    private Application application;
    DefaultTableModel medTableModel;

    /**
     * Creates new form CatalogJPanel
     */
    public CatalogJPanel() {
        initComponents();
    }

    CatalogJPanel(Application application) {
        initComponents();
        this.application = application;
        this.medTableModel=(DefaultTableModel) medicineCatalog.getModel();
        displayMedicineCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicineCatalog = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        dosageField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicineCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 60));
        add(dosageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 50));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void displayMedicineCatalog(){
        ArrayList<Medicine> medicines= this.application.getCatalog().getMedicineList();
        if(medicines.size()>0){
            medTableModel.setRowCount(0);
            for(Medicine med: medicines){
                Object row[]= new Object[2];
                row[0]=med;
                row[1]=med.getDosage();
                
                medTableModel.addRow(row);
            }
        }
    }
    
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        String name= nameField.getText();
        String dosage= dosageField.getText();
        MedicineCatalog catalog= this.application.getCatalog();
        catalog.createMedicine(name, Double.valueOf(dosage));
        JOptionPane.showMessageDialog(null, "medicine added");
        displayMedicineCatalog();
    }//GEN-LAST:event_addBtnActionPerformed

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        // TODO add your handling code here:
        String name= nameField.getText();
        Boolean isUnique= this.application.getCatalog().checkIfMedicineUnique(name);
        
        if(isUnique){
            
        }
        else{
            nameField.setText("");
            JOptionPane.showMessageDialog(null,"Medicine not added");
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow= medicineCatalog.getSelectedRow();
        if(selectedRow>=0){
            Medicine med=(Medicine) medicineCatalog.getValueAt(selectedRow, 0);
            this.application.getCatalog().removeMedicine(med.getMedicineName());
            JOptionPane.showMessageDialog(null,"Row Deleted");
            displayMedicineCatalog();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dosageField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicineCatalog;
    private javax.swing.JTextField nameField;
    // End of variables declaration//GEN-END:variables
}
