/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author nishipancholi
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    private Application application;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        bloodPressureLabel = new javax.swing.JLabel();
        bloodPressureField = new javax.swing.JTextField();
        tempLabel = new javax.swing.JLabel();
        tempField = new javax.swing.JTextField();
        addObservation = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setText("CREATE VITAL SIGN");
        add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 38, -1, -1));

        idLabel.setText("ID");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 98, -1, -1));
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 95, 162, -1));

        bloodPressureLabel.setText("BloodPressure");
        add(bloodPressureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 248, -1, -1));
        add(bloodPressureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 245, 162, -1));

        tempLabel.setText("Temprature");
        add(tempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 173, -1, -1));
        add(tempField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 170, 162, -1));

        addObservation.setText("ADD OBSERVATION");
        addObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObservationActionPerformed(evt);
            }
        });
        add(addObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 324, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObservationActionPerformed
        // TODO add your handling code here:
        VitalSignHistory history=this.application.getHistory();
        
        String id = idField.getText();
        String bloodPressure = bloodPressureField.getText();
        String temp = tempField.getText();
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(bloodPressure), Double.valueOf(temp));
        
        JOptionPane.showMessageDialog(null,"Observation Added");
        
    }//GEN-LAST:event_addObservationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObservation;
    private javax.swing.JTextField bloodPressureField;
    private javax.swing.JLabel bloodPressureLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField tempField;
    private javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
