/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Observations;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishipancholi
 */
public class ViewJPanel extends javax.swing.JPanel {
    private Application application;
    DefaultTableModel viewTableModel;
    private Observations selectedObservation;

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel() {
        initComponents();
    }

    ViewJPanel(Application application) {
        initComponents();
        this.application = application;
        this.viewTableModel= (DefaultTableModel) observationTable.getModel();
        displayObservations();
    }

    public void displayObservations(){
        VitalSignHistory history=this.application.getHistory();
        System.out.println(history.getVitalSignHistory());
        if(history.getVitalSignHistory().size()>0){
            for (Observations o:history.getVitalSignHistory()){
                Object row[]= new Object[3];
                row[0]=o;
                row[1]=o.getTemprature();
                row[2]=o.getBloodPressure();
                
                viewTableModel.addRow(row);
            }
        }
        else{
            System.out.println("Empty List");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        observationTable = new javax.swing.JTable();
        viewObservation = new javax.swing.JButton();
        header = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        bloodPressureLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        tempField = new javax.swing.JTextField();
        bloodPressureField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        observationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Temperature", "BloodPressure"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(observationTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 41, -1, 343));

        viewObservation.setText("View Observation");
        viewObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewObservationActionPerformed(evt);
            }
        });
        add(viewObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 402, -1, -1));

        header.setText("View And Update Observation");
        add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        idLabel.setText("ID");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        tempLabel.setText("Temperature");
        add(tempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        bloodPressureLabel.setText("Blood Pressure");
        add(bloodPressureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        idField.setEnabled(false);
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, -1));
        add(tempField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 160, -1));
        add(bloodPressureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewObservationActionPerformed
        // TODO add your handling code here:
        int selectedRow = observationTable.getSelectedRow();
        if(selectedRow >= 0){
            this.selectedObservation= (Observations) observationTable.getValueAt(selectedRow,0);
            idField.setText(String.valueOf(this.selectedObservation.getObservationId()));
            tempField.setText(String.valueOf(this.selectedObservation.getTemprature()));
            bloodPressureField.setText(String.valueOf(this.selectedObservation.getBloodPressure()));
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Select Row");
        }
    }//GEN-LAST:event_viewObservationActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        this.selectedObservation.setBloodPressure(Double.valueOf(bloodPressureField.getText()));
        this.selectedObservation.setTemprature(Double.valueOf(tempField.getText()));
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodPressureField;
    private javax.swing.JLabel bloodPressureLabel;
    private javax.swing.JLabel header;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable observationTable;
    private javax.swing.JTextField tempField;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewObservation;
    // End of variables declaration//GEN-END:variables
}
