/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import Model.Address;
import Model.Contact;
import Model.Student;
import javax.swing.JOptionPane;

/**
 *
 * @author nishipancholi
 */
public class HuskyCard extends javax.swing.JFrame {

    /**
     * Creates new form HuskyCard
     */
    private Student student;
    public HuskyCard() {
        initComponents();
        this.student=new Student();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitProjectPanel = new javax.swing.JSplitPane();
        InputJPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        nuidLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        collegeNameLabel = new javax.swing.JLabel();
        contactInfoLabel = new javax.swing.JLabel();
        personalContactLabel = new javax.swing.JLabel();
        officeContactLabel = new javax.swing.JLabel();
        personalEmailLabel = new javax.swing.JLabel();
        personalPhoneLabel = new javax.swing.JLabel();
        officeEmailLabel = new javax.swing.JLabel();
        officePhoneLabel = new javax.swing.JLabel();
        localAddressLabel = new javax.swing.JLabel();
        localStreetLabel = new javax.swing.JLabel();
        localCityLabel = new javax.swing.JLabel();
        localApartmentNoLabel = new javax.swing.JLabel();
        localZipCodeLabel = new javax.swing.JLabel();
        nuidInputField = new javax.swing.JTextField();
        firstNameInputField = new javax.swing.JTextField();
        lastNameInputField = new javax.swing.JTextField();
        personalEmailInputField = new javax.swing.JTextField();
        personalPhoneInputField = new javax.swing.JTextField();
        officeEmailInputField = new javax.swing.JTextField();
        officePhoneInputField = new javax.swing.JTextField();
        localCityInputField = new javax.swing.JTextField();
        localZipCodeInputField = new javax.swing.JTextField();
        localApartmentNoInputField = new javax.swing.JTextField();
        localStreetInputField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        collegeNameInputField = new javax.swing.JTextField();
        permanentAddressLabel = new javax.swing.JLabel();
        permanentStreetLabel = new javax.swing.JLabel();
        permanentApartmentNoLabel = new javax.swing.JLabel();
        permanentCityLabel = new javax.swing.JLabel();
        permanentZipCode = new javax.swing.JLabel();
        permanentStreetInputField = new javax.swing.JTextField();
        permanentApartmentNoInputField = new javax.swing.JTextField();
        permanentCityInputField = new javax.swing.JTextField();
        permanentZipCodeInputField = new javax.swing.JTextField();
        CardJPanel = new javax.swing.JPanel();
        huskyCardLabel = new javax.swing.JLabel();
        nuidDisplayLabel = new javax.swing.JLabel();
        nameDisplayLabel = new javax.swing.JLabel();
        collegeDisplayLabel = new javax.swing.JLabel();
        contactInfoDisplayLabel = new javax.swing.JLabel();
        personalDisplayLabel = new javax.swing.JLabel();
        officeDisplayLabel = new javax.swing.JLabel();
        addressDisplayLabel = new javax.swing.JLabel();
        viewNuid = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewCollege = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewOfficeEmail = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewLocalStreet = new javax.swing.JLabel();
        viewLocalApartmentNo = new javax.swing.JLabel();
        viewLocalCity = new javax.swing.JLabel();
        viewLocalZipCode = new javax.swing.JLabel();
        localStreetDisplaylabel = new javax.swing.JLabel();
        localApartmentDisplayLabel = new javax.swing.JLabel();
        localCityDisplayLabel = new javax.swing.JLabel();
        localZipCodeDisplayLabel = new javax.swing.JLabel();
        permanentAddressDisplayLabel = new javax.swing.JLabel();
        permanentStreetDisplayLabel = new javax.swing.JLabel();
        permanentApartmentDisplayLabel = new javax.swing.JLabel();
        permanentCityDisplayLabel = new javax.swing.JLabel();
        permanentZipCodeDisplayLabel = new javax.swing.JLabel();
        viewPermanentStreet = new javax.swing.JLabel();
        viewPermanentApartmentNo = new javax.swing.JLabel();
        viewPermanentCity = new javax.swing.JLabel();
        viewPermanentZipCode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitProjectPanel.setDividerLocation(200);

        InputJPanel.setBackground(new java.awt.Color(204, 204, 255));
        InputJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setText("Welcome !");
        InputJPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        nuidLabel.setText("NUID:");
        InputJPanel.add(nuidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        firstNameLabel.setText("First Name:");
        InputJPanel.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        lastNameLabel.setText("Last Name:");
        InputJPanel.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        collegeNameLabel.setText("College Name:");
        InputJPanel.add(collegeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        contactInfoLabel.setText("Contact Information");
        InputJPanel.add(contactInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        personalContactLabel.setText("Personal");
        InputJPanel.add(personalContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        officeContactLabel.setText("Office");
        InputJPanel.add(officeContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        personalEmailLabel.setText("Email:");
        InputJPanel.add(personalEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        personalPhoneLabel.setText("Phone:");
        InputJPanel.add(personalPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        officeEmailLabel.setText("Email:");
        InputJPanel.add(officeEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        officePhoneLabel.setText("Phone:");
        InputJPanel.add(officePhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        localAddressLabel.setText("Local Address");
        InputJPanel.add(localAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        localStreetLabel.setText("Street:");
        InputJPanel.add(localStreetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        localCityLabel.setText("City:");
        InputJPanel.add(localCityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, 20));

        localApartmentNoLabel.setText("Apartment No:");
        InputJPanel.add(localApartmentNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 90, 20));

        localZipCodeLabel.setText("Zip Code:");
        InputJPanel.add(localZipCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));
        InputJPanel.add(nuidInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 170, -1));

        firstNameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameInputFieldActionPerformed(evt);
            }
        });
        InputJPanel.add(firstNameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 67, 170, -1));

        lastNameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputFieldActionPerformed(evt);
            }
        });
        InputJPanel.add(lastNameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 97, 170, -1));

        personalEmailInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalEmailInputFieldActionPerformed(evt);
            }
        });
        InputJPanel.add(personalEmailInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, -1));
        InputJPanel.add(personalPhoneInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 30));

        officeEmailInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeEmailInputFieldActionPerformed(evt);
            }
        });
        InputJPanel.add(officeEmailInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 190, -1));

        officePhoneInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officePhoneInputFieldActionPerformed(evt);
            }
        });
        InputJPanel.add(officePhoneInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 190, -1));
        InputJPanel.add(localCityInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 160, -1));
        InputJPanel.add(localZipCodeInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 160, -1));
        InputJPanel.add(localApartmentNoInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 160, -1));
        InputJPanel.add(localStreetInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 160, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        InputJPanel.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, -1, -1));
        InputJPanel.add(collegeNameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        permanentAddressLabel.setText("Permanent Address");
        InputJPanel.add(permanentAddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        permanentStreetLabel.setText("Street:");
        InputJPanel.add(permanentStreetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        permanentApartmentNoLabel.setText("Apartment No:");
        InputJPanel.add(permanentApartmentNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        permanentCityLabel.setText("City:");
        InputJPanel.add(permanentCityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        permanentZipCode.setText("Zip Code:");
        InputJPanel.add(permanentZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, -1, -1));
        InputJPanel.add(permanentStreetInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 170, -1));
        InputJPanel.add(permanentApartmentNoInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 150, -1));
        InputJPanel.add(permanentCityInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 190, -1));
        InputJPanel.add(permanentZipCodeInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 180, -1));

        SplitProjectPanel.setLeftComponent(InputJPanel);

        CardJPanel.setBackground(new java.awt.Color(255, 204, 204));
        CardJPanel.setForeground(new java.awt.Color(255, 255, 255));

        huskyCardLabel.setText("HUSKY CARD");

        nuidDisplayLabel.setText("NUID");

        nameDisplayLabel.setText("NAME");

        collegeDisplayLabel.setText("COLLEGE");

        contactInfoDisplayLabel.setText("Contact Information");

        personalDisplayLabel.setText("Personal");

        officeDisplayLabel.setText("Office");

        addressDisplayLabel.setText("Local Address");

        localStreetDisplaylabel.setText("Street");

        localApartmentDisplayLabel.setText("Apartment");

        localCityDisplayLabel.setText("City");

        localZipCodeDisplayLabel.setText("Zip Code");

        permanentAddressDisplayLabel.setText("Permanent Address");

        permanentStreetDisplayLabel.setText("Street");

        permanentApartmentDisplayLabel.setText("Apartment ");

        permanentCityDisplayLabel.setText("City");

        permanentZipCodeDisplayLabel.setText("Zip Code");

        javax.swing.GroupLayout CardJPanelLayout = new javax.swing.GroupLayout(CardJPanel);
        CardJPanel.setLayout(CardJPanelLayout);
        CardJPanelLayout.setHorizontalGroup(
            CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardJPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewNuid, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CardJPanelLayout.createSequentialGroup()
                        .addComponent(viewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(164, 164, 164))
            .addGroup(CardJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardJPanelLayout.createSequentialGroup()
                        .addComponent(localStreetDisplaylabel)
                        .addGap(56, 56, 56)
                        .addComponent(viewLocalStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CardJPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(huskyCardLabel)
                            .addComponent(addressDisplayLabel)
                            .addGroup(CardJPanelLayout.createSequentialGroup()
                                .addComponent(personalDisplayLabel)
                                .addGap(112, 112, 112)
                                .addComponent(officeDisplayLabel))
                            .addComponent(contactInfoDisplayLabel)
                            .addGroup(CardJPanelLayout.createSequentialGroup()
                                .addComponent(collegeDisplayLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameDisplayLabel)
                            .addComponent(nuidDisplayLabel)
                            .addGroup(CardJPanelLayout.createSequentialGroup()
                                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CardJPanelLayout.createSequentialGroup()
                                        .addComponent(viewOfficePhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(20, 20, 20))))))
                    .addComponent(permanentAddressDisplayLabel)
                    .addGroup(CardJPanelLayout.createSequentialGroup()
                        .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(localApartmentDisplayLabel)
                            .addComponent(localCityDisplayLabel))
                        .addGap(30, 30, 30)
                        .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewLocalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewLocalApartmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CardJPanelLayout.createSequentialGroup()
                            .addComponent(localZipCodeDisplayLabel)
                            .addGap(28, 28, 28)
                            .addComponent(viewLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CardJPanelLayout.createSequentialGroup()
                            .addComponent(permanentCityDisplayLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewPermanentCity, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                .addComponent(viewPermanentZipCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(permanentZipCodeDisplayLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(CardJPanelLayout.createSequentialGroup()
                        .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(permanentStreetDisplayLabel)
                            .addComponent(permanentApartmentDisplayLabel))
                        .addGap(38, 38, 38)
                        .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPermanentApartmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewPermanentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(162, 260, Short.MAX_VALUE))
        );
        CardJPanelLayout.setVerticalGroup(
            CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(huskyCardLabel)
                .addGap(27, 27, 27)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nuidDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewNuid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDisplayLabel)
                    .addComponent(viewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collegeDisplayLabel)
                    .addComponent(viewCollege))
                .addGap(18, 18, 18)
                .addComponent(contactInfoDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalDisplayLabel)
                    .addComponent(officeDisplayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewPersonalEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(viewOfficeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(addressDisplayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLocalStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localStreetDisplaylabel))
                .addGap(18, 18, 18)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLocalApartmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localApartmentDisplayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewLocalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(localCityDisplayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(localZipCodeDisplayLabel)
                    .addComponent(viewLocalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(permanentAddressDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardJPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(viewPermanentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardJPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(permanentStreetDisplayLabel)
                        .addGap(29, 29, 29)))
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardJPanelLayout.createSequentialGroup()
                        .addComponent(viewPermanentApartmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(viewPermanentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardJPanelLayout.createSequentialGroup()
                        .addComponent(permanentApartmentDisplayLabel)
                        .addGap(18, 18, 18)
                        .addComponent(permanentCityDisplayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(CardJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(permanentZipCodeDisplayLabel)
                    .addComponent(viewPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        SplitProjectPanel.setRightComponent(CardJPanel);

        getContentPane().add(SplitProjectPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameInputFieldActionPerformed

    private void lastNameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputFieldActionPerformed

    private void personalEmailInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalEmailInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalEmailInputFieldActionPerformed

    private void officeEmailInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeEmailInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officeEmailInputFieldActionPerformed

    private void officePhoneInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officePhoneInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officePhoneInputFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int nuid= Integer.parseInt(nuidInputField.getText());
        String firstName= firstNameInputField.getText();
        String lastName= lastNameInputField.getText();
        String collegeName= collegeNameInputField.getText();
        int personalPhone= Integer.parseInt(personalPhoneInputField.getText());
        String personalEmail= personalEmailInputField.getText();
        int officePhone= Integer.parseInt(officePhoneInputField.getText());
        String officeEmail= officeEmailInputField.getText();
        String localStreet= localStreetInputField.getText();
        String localCity= localCityInputField.getText();
        int localApartmentNo= Integer.parseInt(localApartmentNoInputField.getText());
        int localZipCode= Integer.parseInt(localZipCodeInputField.getText());
        String permanentStreet= permanentStreetInputField.getText();
        String permanentCity= permanentCityInputField.getText();
        int permanentApartmentNo= Integer.parseInt(permanentApartmentNoInputField.getText());
        int permanentZipCode= Integer.parseInt(permanentZipCodeInputField.getText());

        this.student.setNuid(nuid);
        this.student.setFirstName(firstName);
        this.student.setLastName(lastName);
        this.student.setCollegeName(collegeName);
        
        Contact personalContact= this.student.getPersonalContact();
        personalContact.setEmail(personalEmail);
        personalContact.setPhoneNumber(personalPhone);
        
        Contact officeContact= this.student.getOfficeContact();
        officeContact.setEmail(officeEmail);
        officeContact.setPhoneNumber(officePhone);
        
        Address localAddress=this.student.getLocalAddress();
        localAddress.setStreet(localStreet);
        localAddress.setAptNo(localApartmentNo);
        localAddress.setCity(localCity);
        localAddress.setZipCode(localZipCode);
        
        Address permanentAddress=this.student.getPermanentAddress();
        permanentAddress.setStreet(permanentStreet);
        permanentAddress.setAptNo(permanentApartmentNo);
        permanentAddress.setCity(permanentCity);
        permanentAddress.setZipCode(permanentZipCode);
        
        JOptionPane.showMessageDialog(null, "Saved Successfully!");
        display();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void display(){
        viewNuid.setText(Integer.toString(this.student.getNuid()));
        viewFirstName.setText(this.student.getFirstName());
        viewLastName.setText(this.student.getLastName());
        viewCollege.setText(this.student.getCollegeName());
        
        viewPersonalPhone.setText(Integer.toString(this.student.getPersonalContact().getPhoneNumber()));
        viewPersonalEmail.setText(this.student.getPersonalContact().getEmail());
        viewOfficePhone.setText(Integer.toString(this.student.getOfficeContact().getPhoneNumber()));
        viewOfficeEmail.setText(this.student.getOfficeContact().getEmail());
        
        viewLocalStreet.setText(this.student.getLocalAddress().getStreet());
        viewLocalApartmentNo.setText(Integer.toString(this.student.getLocalAddress().getAptNo()));
        viewLocalCity.setText(this.student.getLocalAddress().getCity());
        viewLocalZipCode.setText(Integer.toString(this.student.getLocalAddress().getZipCode()));
        
        viewPermanentStreet.setText(this.student.getPermanentAddress().getStreet());
        viewPermanentApartmentNo.setText(Integer.toString(this.student.getPermanentAddress().getAptNo()));
        viewPermanentCity.setText(this.student.getPermanentAddress().getCity());
        viewPermanentZipCode.setText(Integer.toString(this.student.getPermanentAddress().getZipCode()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuskyCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuskyCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardJPanel;
    private javax.swing.JPanel InputJPanel;
    private javax.swing.JSplitPane SplitProjectPanel;
    private javax.swing.JLabel addressDisplayLabel;
    private javax.swing.JLabel collegeDisplayLabel;
    private javax.swing.JTextField collegeNameInputField;
    private javax.swing.JLabel collegeNameLabel;
    private javax.swing.JLabel contactInfoDisplayLabel;
    private javax.swing.JLabel contactInfoLabel;
    private javax.swing.JTextField firstNameInputField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel huskyCardLabel;
    private javax.swing.JTextField lastNameInputField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel localAddressLabel;
    private javax.swing.JLabel localApartmentDisplayLabel;
    private javax.swing.JTextField localApartmentNoInputField;
    private javax.swing.JLabel localApartmentNoLabel;
    private javax.swing.JLabel localCityDisplayLabel;
    private javax.swing.JTextField localCityInputField;
    private javax.swing.JLabel localCityLabel;
    private javax.swing.JLabel localStreetDisplaylabel;
    private javax.swing.JTextField localStreetInputField;
    private javax.swing.JLabel localStreetLabel;
    private javax.swing.JLabel localZipCodeDisplayLabel;
    private javax.swing.JTextField localZipCodeInputField;
    private javax.swing.JLabel localZipCodeLabel;
    private javax.swing.JLabel nameDisplayLabel;
    private javax.swing.JLabel nuidDisplayLabel;
    private javax.swing.JTextField nuidInputField;
    private javax.swing.JLabel nuidLabel;
    private javax.swing.JLabel officeContactLabel;
    private javax.swing.JLabel officeDisplayLabel;
    private javax.swing.JTextField officeEmailInputField;
    private javax.swing.JLabel officeEmailLabel;
    private javax.swing.JTextField officePhoneInputField;
    private javax.swing.JLabel officePhoneLabel;
    private javax.swing.JLabel permanentAddressDisplayLabel;
    private javax.swing.JLabel permanentAddressLabel;
    private javax.swing.JLabel permanentApartmentDisplayLabel;
    private javax.swing.JTextField permanentApartmentNoInputField;
    private javax.swing.JLabel permanentApartmentNoLabel;
    private javax.swing.JLabel permanentCityDisplayLabel;
    private javax.swing.JTextField permanentCityInputField;
    private javax.swing.JLabel permanentCityLabel;
    private javax.swing.JLabel permanentStreetDisplayLabel;
    private javax.swing.JTextField permanentStreetInputField;
    private javax.swing.JLabel permanentStreetLabel;
    private javax.swing.JLabel permanentZipCode;
    private javax.swing.JLabel permanentZipCodeDisplayLabel;
    private javax.swing.JTextField permanentZipCodeInputField;
    private javax.swing.JLabel personalContactLabel;
    private javax.swing.JLabel personalDisplayLabel;
    private javax.swing.JTextField personalEmailInputField;
    private javax.swing.JLabel personalEmailLabel;
    private javax.swing.JTextField personalPhoneInputField;
    private javax.swing.JLabel personalPhoneLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel viewCollege;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewLocalApartmentNo;
    private javax.swing.JLabel viewLocalCity;
    private javax.swing.JLabel viewLocalStreet;
    private javax.swing.JLabel viewLocalZipCode;
    private javax.swing.JLabel viewNuid;
    private javax.swing.JLabel viewOfficeEmail;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewPermanentApartmentNo;
    private javax.swing.JLabel viewPermanentCity;
    private javax.swing.JLabel viewPermanentStreet;
    private javax.swing.JLabel viewPermanentZipCode;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
